### ISSUE TITLE
[FEATURE] Cloudflare R2 (S3) Support

### ISSUE THREAD

**Issue by Permanently** [tycrek/ass#155]
### Description

This is pretty much a ticket to check whether Cloudflare R2 is supported. Cloudflare says it's somewhat compatible, depending on what's used. [Documentation & compatibility can be viewed here.](https://developers.cloudflare.com/r2/platform/s3-compatibility/api/)

**Comment by nischay876** [comment]
[R2 via CF Worker](https://developers.cloudflare.com/r2/examples/demo-worker/)
https://developers.cloudflare.com/r2/get-started/

**Comment by tycrek** [comment]
I looked into this for a bit and tried a bunch of different methods but couldn't get the `aws-sdk` library to work with it. Perhaps someone else would have better luck.

I also looked into the Workers method... yikes. Far more work effort than I feel like most hosts would be willing to put in. At that point you're basically just writing two file upload servers.

So in summary: R2 is **unsupported** for now. If Cloudflare improves their implementation of S3 in the future, this may change.

**Comment by LeagueRaINi** [comment]
Any updates on this? r2 s3 compat seems good enough now, i had to edit `getS3url` to serve from a different domain than the private s3 endpoint and have that running fine atm

as to why i had to edit the src, i'm pretty new to r2 so i dont know if there is a different way i'm not aware of but it seems like r2 has a private api endpoint for api calls and then u set a different domain for serving (that one cannot interact with the api from my testing) which is why i had to edit `getS3url`, that domain also doesnt seems to support any of the path styles you are using (eg `bucket.domain` and `domain/bucket`), its just the domain, not sure how that would be integrated (if u even plan to)

**Comment by Permanently** [comment]
I've been using Cloudflare R2 with Mastodon, which is mainly S3-oriented. I've had no issues with it whatsoever.

But, it's not my call to say whether it's safe to use or not. That's just my experience.

**Comment by tycrek** [comment]
I'm more inclined to support it now, though it would be a feature for 0.15.0 (see PR #220)
